joy_node:
  ros__parameters:
    deadzone: 0.15
    autorepeat_rate: 10.0

teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: False
    enable_button: 0
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.5
      y: 0.5
    axis_angular.z: 2
    scale_angular.yaw: 1.57